# Generated by Django 5.1.15 on 2026-04-03 19:04

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_new_simulations', models.BooleanField(default=True)),
                ('threshold_up', models.FloatField()),
                ('threshold_down', models.FloatField()),
                ('apy_up', models.FloatField()),
                ('apy_down', models.FloatField()),
                ('initial_usdc', models.FloatField()),
                ('interval', models.IntegerField(help_text='Number of days per iteration')),
            ],
            options={
                'verbose_name_plural': 'Settings',
            },
        ),
        migrations.CreateModel(
            name='Simulation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('threshold_up', models.FloatField()),
                ('threshold_down', models.FloatField()),
                ('apy_up', models.FloatField()),
                ('apy_down', models.FloatField()),
                ('initial_usdc', models.FloatField()),
                ('starter_btc_price', models.FloatField()),
                ('interval', models.IntegerField()),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SimulationBalance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('usdc_amount', models.FloatField(default=0)),
                ('btc_amount', models.FloatField(default=0)),
                ('btc_price', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('simulation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balances', to='core.simulation')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
